### ISSUE TITLE
[Bug]: cannot install the package by amd64 installation script

### ISSUE THREAD

**Issue by lxsy-xcy** [Interbotix/interbotix_ros_rovers#21]
### What happened?

I want to install this package on my locobot , so I fellow the tutorial and run the script, but it failed and told me that can't find "$BRIDGE_MSGS_ROS1_WS/install_isolated/setup.bash".

I read the script and find that if I choose the kobuki base, I will not have that file, because BRIDGE_MSGS_ROS1_WS only have create3 base version.

And I wonder that if I choose ros1 to install, can I install the realsense by this script? I don't find the script to install that in ros1.

(I am not an English speaker and I hope I express my issue correctly.)

### Robot Model

locobot_wx250s

### Operating System

Ubuntu 18.04

### ROS Distro

ROS1 Melodic

### Steps To Reproduce

./xslocobot_remote_install.sh -b kobuki 
(with 18.04 ubuntu and ros 1 melodic)

**Comment by LSinterbotix** [comment]
This should be fixed with the above commit. Feel free to reopen this issue if not.

**Comment by lxsy-xcy** [comment]
I have another question about the script. I wonder that if I choose ros1 to install, can I install the realsense by this script? I don't find the script to install that in ros1.

**Comment by LSinterbotix** [comment]
It is installed via rosdep since interbotix_xslocobot_control depends on it via its package.xml file:

https://github.com/Interbotix/interbotix_ros_rovers/blob/8a8af5addbb7256f1051a0e1b4d0e3cc59d2c5f2/interbotix_ros_xslocobots/install/amd64/xslocobot_amd64_install.sh#L328

https://github.com/Interbotix/interbotix_ros_rovers/blob/ea7bfb523ded49599e6eb4e4fafb9c4a07f77717/interbotix_ros_xslocobots/interbotix_xslocobot_control/package.xml#L19

**Comment by lxsy-xcy** [comment]
thank you very much! I’ll try that.

**Comment by lxsy-xcy** [comment]
Thank you very much! I’ll try that.
